function sx(x){return Math.round(x-camera.x+canvas.width/2)}function sy(y){return Math.round(y-camera.y+canvas.height/2)}
function drawSprite(sheet,cellW,cellH,col,row,x,y,scale=1){if(!sheet.complete||!sheet.naturalWidth)return false;ctx.drawImage(sheet,col*cellW,row*cellH,cellW,cellH,Math.round(x-cellW*scale/2),Math.round(y-cellH*scale*.76),cellW*scale,cellH*scale);return true}
function directionRow(dir){const x=Math.cos(dir),y=Math.sin(dir);if(Math.abs(y)>Math.abs(x))return y>0?0:3;return x<0?1:2}
function draw(){resizeCanvas();const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);camera.x=lerp(camera.x,me.x,.10);camera.y=lerp(camera.y,me.y,.10);drawGround(W,H);drawCamp(W,H);drawResources(W,H);drawMobs(W,H);for(const p of remotes.values())drawPlayer(p,false);drawPlayer(me,true);drawLighting(W,H);requestAnimationFrame(draw)}
function drawGround(W,H){const biome=BIOMES[currentZone]||['UNKNOWN','#466f54','#64875f'],ts=24,minX=Math.floor((camera.x-W/2)/ts)-1,maxX=Math.ceil((camera.x+W/2)/ts)+1,minY=Math.floor((camera.y-H/2)/ts)-1,maxY=Math.ceil((camera.y+H/2)/ts)+1;ctx.fillStyle=biome[1];ctx.fillRect(0,0,W,H);for(let ty=minY;ty<=maxY;ty++)for(let tx=minX;tx<=maxX;tx++){const wx=tx*ts,wy=ty*ts,h=hash(tx,ty,17),safe=campDist(wx+12,wy+12)<CAMP.r;const x=sx(wx),y=sy(wy);ctx.fillStyle=safe?(h>.78?'#78966e':'#6f9067'):(h>.84?biome[2]:(h<.10?'#294c40':biome[1]));ctx.fillRect(x,y,ts+1,ts+1);if(!safe&&hash(tx,ty,99)>.967){ctx.fillStyle='#355e50';ctx.fillRect(x+4,y+7,3,8);ctx.fillRect(x+12,y+3,2,10)}if(safe&&h>.91){ctx.fillStyle='#9da66d';ctx.fillRect(x+5,y+9,2,2);ctx.fillRect(x+15,y+5,2,2)}}}
function prop(index,x,y,scale=1){drawSprite(img.props,48,48,index%4,Math.floor(index/4),sx(x),sy(y),scale)}
function drawCamp(W,H){if(currentZone!=='1:1')return;const cx=sx(CAMP.x),cy=sy(CAMP.y);ctx.strokeStyle='#9fc8a6';ctx.lineWidth=2;ctx.setLineDash([5,6]);ctx.beginPath();ctx.arc(cx,cy,CAMP.r,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);prop(0,CAMP.x,CAMP.y,1.15);prop(1,CAMP.x-180,CAMP.y-120,1.2);prop(1,CAMP.x+180,CAMP.y-115,1.2);prop(2,CAMP.x-205,CAMP.y+135,1.15);prop(3,CAMP.x+190,CAMP.y+140,1.05);prop(5,CAMP.x,CAMP.y-CAMP.r+25,1.2);prop(7,CAMP.x,CAMP.y-CAMP.r+85,1.0);prop(6,CAMP.x-250,CAMP.y-250,1);prop(6,CAMP.x+250,CAMP.y-250,1);for(let i=-3;i<=3;i++){if(i!==0)prop(4,CAMP.x+i*75,CAMP.y-CAMP.r+18,.95)}ctx.fillStyle='#f0e8bd';ctx.font='bold 8px monospace';ctx.textAlign='center';ctx.fillText('MIREWOOD SAFE CAMP',cx,sy(CAMP.y-CAMP.r+105))}
function drawResources(W,H){const frameMap={wood:0,stone:1,food:2,shard:3};for(const r of resources){if((harvested.get(r.id)||0)>Date.now())continue;const x=sx(r.x),y=sy(r.y);if(x<-30||y<-30||x>W+30||y>H+30)continue;if(!drawSprite(img.resources,32,32,frameMap[r.type],0,x,y,.85)){ctx.fillStyle='#d7d0a5';ctx.fillRect(x-4,y-4,8,8)}}}
function drawMobs(W,H){const t=performance.now()/180;for(const m of mobs){if(m.hp<=0)continue;const x=sx(m.x),y=sy(m.y);if(x<-45||y<-45||x>W+45||y>H+45)continue;const row=m.kind==='watcher'?0:(m.kind==='cultist'?1:2),frame=Math.floor(t+m.phase)%4;if(!drawSprite(img.monsters,32,32,frame,row,x,y,1.2)){ctx.fillStyle='#223b33';ctx.fillRect(x-10,y-10,20,20)}}}
function drawPlayer(p,self){const x=sx(p.x),y=sy(p.y),row=directionRow(p.dir||0),moving=self?isMoving:!!p.moving,frame=moving?(self?Math.floor(walkClock)%4:Math.floor(performance.now()/150+(p.id?.length||0))%4):0;drawSprite(img.player,24,32,frame,row,x,y,1.18);if(!self){ctx.strokeStyle=p.color||'#9cb0a7';ctx.lineWidth=1;ctx.strokeRect(x-9,y-20,18,26)}if((self?attackFlash:p.attack)>0){ctx.strokeStyle='#f0ddb2';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,27,(p.dir||0)-.8,(p.dir||0)+.8);ctx.stroke()}if(self&&(Date.now()<invulnerableUntil||Date.now()<fieldGraceUntil)){ctx.strokeStyle='#b3ead2';ctx.beginPath();ctx.arc(x,y,18,0,Math.PI*2);ctx.stroke()}ctx.fillStyle='#f6f3de';ctx.font='bold 7px monospace';ctx.textAlign='center';ctx.fillText(clean(p.name),x,y-25)}
function drawLighting(W,H){let n=nightLevel();if(inCamp())n=Math.min(n,.08);const insanity=1-me.sanity/100;if(n>0){ctx.fillStyle=`rgba(3,10,14,${n*.42})`;ctx.fillRect(0,0,W,H)}if(!inCamp()&&(n>.18||insanity>.32)){const radius=inventory.lantern?150:105,px=sx(me.x),py=sy(me.y),g=ctx.createRadialGradient(px,py,20,px,py,radius);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(.6,'rgba(0,0,0,0)');g.addColorStop(1,`rgba(0,4,7,${.34+n*.36})`);ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}if(insanity>.35){ctx.fillStyle=`rgba(65,25,69,${insanity*.075})`;ctx.fillRect(0,0,W,H)}}
setInterval(()=>{const now=performance.now(),dt=clamp((now-lastTick)/1000,0,.05);lastTick=now;update(dt)},33);requestAnimationFrame(draw);updateUI();