import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../modules/render/awakening-macro-terrain-prototype-v1.js',import.meta.url),'utf8');
const page=fs.readFileSync(new URL('../awakening-macro-terrain-prototype-v1.html',import.meta.url),'utf8');
const boot=fs.readFileSync(new URL('../survival-v21.html',import.meta.url),'utf8');
for(const forbidden of ['COLLISION','resolveMovement','harvestResource','handleMobAttack','RELAY_URL','saveLocal','sendMove'])assert.equal(source.includes(forbidden),false,`prototype must remain presentation-only: ${forbidden}`);
assert.equal(source.includes('Math.random'),false,'macro placement must never vary randomly per frame');assert.equal(page.includes('Math.random'),false,'preview placement must remain deterministic');
assert.equal(boot.includes('awakening-macro-terrain-prototype-v1.js'),false,'prototype must not enter normal gameplay boot');
assert.ok(page.includes("terrainSheet.src='assets/art-v21/terrain-v21.png'"),'A/C must use the current V21 64x64 terrain atlas as the baseline');
for(const ref of ['S03.png','S04.png','S05.png'])assert.ok(page.includes(ref),`missing macro reference slot ${ref}`);
for(const viewport of ['1280,720','390,844'])assert.ok(page.includes(viewport),`missing benchmark viewport ${viewport}`);
assert.ok(page.includes('frame avg')&&page.includes('p95')&&page.includes('draw ${s.drawCalls}'),'preview must report draw calls/FPS/frame avg/p95');
const sandbox={window:null,console,Image:class{constructor(){this.naturalWidth=384;this.naturalHeight=384;}set src(v){this._src=v;}},performance:{now:()=>16}};sandbox.window=sandbox;vm.createContext(sandbox);vm.runInContext(source,sandbox);
const api=sandbox.ABYSSAL_MACRO_TERRAIN_PROTOTYPE_V1;assert.ok(api);assert.equal(api.tileSize,64);assert.deepEqual([...api.allowedCells],[3,4,6]);
api.setPatches([{id:'p3',x:64,y:64,cells:3,src:'S03.png'},{id:'p4',x:640,y:640,cells:4,src:'S04.png'},{id:'p6',x:1280,y:1280,cells:6,src:'S05.png'}]);
const p3=api.state.patches.find(p=>p.id==='p3'),p4=api.state.patches.find(p=>p.id==='p4'),p6=api.state.patches.find(p=>p.id==='p6');assert.equal(p3.w,192);assert.equal(p4.w,256);assert.equal(p6.w,384);
assert.equal(api.visiblePatches({x:160,y:160},320,320).some(p=>p.id==='p3'),true);assert.equal(api.visiblePatches({x:160,y:160},320,320).some(p=>p.id==='p6'),false,'offscreen macro patch must be culled');
const ctx={save(){},restore(){},drawImage(){this.calls=(this.calls||0)+1;},imageSmoothingEnabled:true,globalAlpha:1};api.state.images.set('S03.png',{image:{naturalWidth:192,naturalHeight:192},ready:true});
api.beginFrame(10);let r=api.render({ctx,camera:{x:160,y:160},W:320,H:320,mode:'A'});assert.equal(r.drawn,0,'A is current 64x64 base only');r=api.render({ctx,camera:{x:160,y:160},W:320,H:320,mode:'C'});assert.equal(r.drawn,1);assert.equal(r.missing.length,0);assert.equal(ctx.imageSmoothingEnabled,true,'renderer must restore caller smoothing state');assert.equal(ctx.globalAlpha,1,'renderer must restore caller alpha state');let stats=api.endFrame(14);assert.equal(stats.drawCalls,1);
api.beginFrame(26);r=api.render({ctx,camera:{x:160,y:160},W:320,H:320,mode:'B'});stats=api.endFrame(30);assert.equal(stats.avgMs,16,'avg frame time must use requestAnimationFrame interval');assert.equal(stats.p95Ms,16);assert.equal(stats.fps,62.5);assert.equal(stats.renderAvgMs,4,'render timing remains separately observable');
const a=api.normalizePatch({id:'stable',x:129,y:191,cells:4}),b=api.normalizePatch({id:'stable',x:129,y:191,cells:4});assert.deepEqual(a,b,'placement must be deterministic and cell-snapped');assert.equal(a.x,128);assert.equal(a.y,128);
api.state.images.delete('S03.png');r=api.render({ctx,camera:{x:160,y:160},W:320,H:320,mode:'C'});assert.equal(r.missing.some(p=>p.id==='p3'),true,'missing high-quality reference must fall back instead of disappearing silently');
console.log(JSON.stringify({ok:true,presentationOnly:true,tileSize:64,macroCells:api.allowedCells,culling:true,deterministic:true,modes:['A','B','C'],baseline:'current-v21-atlas',telemetry:['draw-calls','fps','frame-avg','frame-p95','render-avg']}));