const STORAGE_KEY = 'deep-sea-duo-language';

const COPY = Object.freeze({
  zh: Object.freeze({
    gameTitle: '深海搭档', subtitle: 'DEEP SEA DUO · 双人深海生存', roomLan: '局域网 / 热点双人直连',
    createRoom: '创建房间', joinRoom: '加入房间', creatingRoom: '正在创建 6 位房间码…', hostWaiting: '房间已创建，等待朋友输入房间码…', joiningRoom: '正在自动连接房间…', yourRoomCode: '你的房间码', tellFriendCode: '把这 6 位数字告诉朋友即可', enterRoomCode: '输入朋友的 6 位房间码', connectRoom: '连接房间', backToLobby: '返回大厅', quickPairHint: '正常情况只需要 6 位房间码，不需要复制长连接码。', invalidRoomCode: '请输入完整的 6 位数字房间码', roomNotFound: '没有找到这个房间，请确认 6 位数字是否正确', roomUnavailable: '这个房间已被加入或已失效，请让房主重新创建', roomExpired: '房间码已过期，请让房主重新创建', signalUnavailable: '自动联机服务暂时不可用，可以稍后重试或展开高级备用连接', signalTimeout: '自动联机请求超时，请检查两台手机是否能上网',
    roomSameNetwork: '两台手机连接同一个 Wi‑Fi，或一台开热点让另一台连接。', manualFallbackTitle: '高级备用：无网时手动连接', manualFallbackHint: '只有信令服务不可用、但两台手机仍在同一局域网时才需要这里。', manualCreate: '生成房主长码', manualJoin: '使用房主长码', manualCodePlaceholder: '高级备用连接码', manualContinue: '继续手动连接', manualCreating: '正在生成手动连接信息…', manualHostReady: '房主长码已生成，把它发给朋友', manualGuestReady: '应答长码已生成，把它发回房主', manualPasteOffer: '粘贴房主长码后继续', manualAcceptAnswer: '粘贴朋友应答码后确认', manualGenerateAnswer: '生成应答长码',
    connected: '局域网直连成功', connecting: '正在建立局域网直连…', disconnected: '连接暂时中断，请返回大厅重新连接', failed: '局域网直连失败，请确认两台手机在同一网络', closed: '连接已断开，可以重新连接', connectionError: '连接发生错误，请重新连接', waitingDirect: '信令交换完成，正在建立局域网直连…', pairingReset: '已返回大厅，可以重新创建或加入房间',
    pasteOffer: '粘贴房主连接码', needGuestAnswer: '请先把朋友发回的应答长码粘贴到这里', needHostOffer: '请先粘贴房主长码', errorIceTimeout: '生成局域网连接信息超时，请切换 Wi‑Fi/热点后重试', errorInvalidCode: '高级连接码格式不正确，请完整复制后再试', errorExpectedAnswer: '房主这里需要加入者的应答长码', errorExpectedOffer: '加入者这里需要房主长码', errorHostNotReady: '请先创建房间',
    dash: '冲刺', moveHint: '左侧滑动移动', aimHint: '右侧拖动瞄准并发射', rotateTitle: '横屏体验更好', rotateBody: '请把手机转成横屏，再继续深海冒险。', evolution: '荧光进化', chooseUpgrade: '选择一项强化', food: '食物', bossName: '深海鲨影', bossApproach: '鲨影正在逼近！', gameOverTitle: '深海暂时沉寂', survived: '存活 {seconds} 秒', restart: '点击画面重新开始', languageButton: 'EN', languageAria: '切换为英文', audioOn: '声音 开', audioOff: '声音 关', audioAria: '切换声音', level: '等级', powerup_shield: '荧光护盾', powerup_heal: '治疗气泡', powerup_wave: '清场海浪', upgrade_power_label: '泡泡增压', upgrade_power_detail: '水弹伤害 +1', upgrade_rapid_label: '连射珊瑚', upgrade_rapid_detail: '攻击间隔 -18%', upgrade_swift_label: '潮汐步伐', upgrade_swift_detail: '移动速度 +12%', upgrade_vital_label: '荧光甲壳', upgrade_vital_detail: '回复 1 点生命', upgrade_wide_label: '泡泡膨胀', upgrade_wide_detail: '水弹体积 +22%', upgrade_haste_label: '急流冲刺', upgrade_haste_detail: '冲刺冷却 -18%',
  }),
  en: Object.freeze({
    gameTitle: 'Deep Sea Duo', subtitle: 'DEEP SEA DUO · CO-OP ABYSS SURVIVAL', roomLan: 'Two-player LAN / hotspot direct link',
    createRoom: 'Create Room', joinRoom: 'Join Room', creatingRoom: 'Creating a 6-digit room code…', hostWaiting: 'Room ready. Waiting for your friend to enter the code…', joiningRoom: 'Connecting automatically…', yourRoomCode: 'Your room code', tellFriendCode: 'Tell your friend these 6 digits', enterRoomCode: 'Enter your friend’s 6-digit room code', connectRoom: 'Connect', backToLobby: 'Back to Lobby', quickPairHint: 'Normally you only need the 6-digit room code. No long codes to copy.', invalidRoomCode: 'Enter the complete 6-digit room code', roomNotFound: 'Room not found. Check the 6 digits and try again.', roomUnavailable: 'This room was already joined or expired. Ask the host to create another.', roomExpired: 'Room code expired. Ask the host to create another.', signalUnavailable: 'Automatic pairing is temporarily unavailable. Retry later or use the advanced fallback.', signalTimeout: 'Automatic pairing timed out. Check that both phones can access the internet.',
    roomSameNetwork: 'Put both phones on the same Wi-Fi, or connect one phone to the other phone’s hotspot.', manualFallbackTitle: 'Advanced fallback: manual LAN pairing', manualFallbackHint: 'Only use this if signaling is unavailable while both phones are still on the same LAN.', manualCreate: 'Generate Host Long Code', manualJoin: 'Use Host Long Code', manualCodePlaceholder: 'Advanced fallback connection code', manualContinue: 'Continue Manual Pairing', manualCreating: 'Generating manual connection info…', manualHostReady: 'Host long code ready. Send it to your friend.', manualGuestReady: 'Answer long code ready. Send it back to the host.', manualPasteOffer: 'Paste the host long code, then continue.', manualAcceptAnswer: 'Paste the guest answer, then confirm', manualGenerateAnswer: 'Generate Answer Long Code',
    connected: 'LAN direct link connected', connecting: 'Establishing LAN direct link…', disconnected: 'Connection interrupted. Return to the lobby and reconnect.', failed: 'LAN direct link failed. Check that both phones are on the same network.', closed: 'Connection closed. You can reconnect.', connectionError: 'Connection error. Try pairing again.', waitingDirect: 'Signaling complete. Establishing the LAN direct link…', pairingReset: 'Back in the lobby. Create or join a room again.',
    pasteOffer: 'Paste host connection code', needGuestAnswer: 'Paste the guest answer long code here first.', needHostOffer: 'Paste the host long code first.', errorIceTimeout: 'LAN connection info timed out. Switch Wi-Fi/hotspot and try again.', errorInvalidCode: 'Invalid advanced connection code. Copy the complete code and try again.', errorExpectedAnswer: 'The host needs the guest answer long code here.', errorExpectedOffer: 'The guest needs the host long code here.', errorHostNotReady: 'Create a room first.',
    dash: 'DASH', moveHint: 'Slide left side to move', aimHint: 'Drag right side to aim & fire', rotateTitle: 'Landscape recommended', rotateBody: 'Rotate your phone to landscape before diving in.', evolution: 'LUMINOUS EVOLUTION', chooseUpgrade: 'Choose one upgrade', food: 'food', bossName: 'Abyss Shark', bossApproach: 'The abyss shark is closing in!', gameOverTitle: 'The deep sea falls quiet', survived: 'Survived {seconds}s', restart: 'Tap the screen to restart', languageButton: '中文', languageAria: 'Switch to Chinese', audioOn: 'Sound On', audioOff: 'Sound Off', audioAria: 'Toggle sound', level: 'Lv.', powerup_shield: 'Luminous Shield', powerup_heal: 'Healing Bubble', powerup_wave: 'Clearing Wave', upgrade_power_label: 'Bubble Pressure', upgrade_power_detail: 'Bubble damage +1', upgrade_rapid_label: 'Rapid Coral', upgrade_rapid_detail: 'Attack interval -18%', upgrade_swift_label: 'Tidal Steps', upgrade_swift_detail: 'Move speed +12%', upgrade_vital_label: 'Glow Shell', upgrade_vital_detail: 'Restore 1 HP', upgrade_wide_label: 'Expanded Bubble', upgrade_wide_detail: 'Bubble size +22%', upgrade_haste_label: 'Rush Current', upgrade_haste_detail: 'Dash cooldown -18%',
  }),
});

function storage() { try { return globalThis.localStorage; } catch { return null; } }
function initialLanguage() { const saved = storage()?.getItem(STORAGE_KEY); return saved === 'en' || saved === 'zh' ? saved : 'zh'; }
let language = initialLanguage();
const listeners = new Set();
export function getLanguage() { return language; }
export function setLanguage(next, { persist = true } = {}) { language = next === 'en' ? 'en' : 'zh'; if (persist) { try { storage()?.setItem(STORAGE_KEY, language); } catch {} } for (const listener of listeners) listener(language); return language; }
export function toggleLanguage() { return setLanguage(language === 'zh' ? 'en' : 'zh'); }
export function t(key, params = {}) { const template = COPY[language][key] ?? COPY.zh[key] ?? key; return Object.entries(params).reduce((value, [name, replacement]) => value.replaceAll(`{${name}}`, String(replacement)), template); }
export function upgradeText(id) { return { label: t(`upgrade_${id}_label`), detail: t(`upgrade_${id}_detail`) }; }
export function powerupText(type) { return t(`powerup_${type}`); }
export function onLanguageChange(listener) { listeners.add(listener); return () => listeners.delete(listener); }
export function applyDocumentTranslations(root = globalThis.document) { if (!root?.querySelectorAll) return; root.documentElement?.setAttribute?.('lang', language === 'zh' ? 'zh-CN' : 'en'); for (const node of root.querySelectorAll('[data-i18n]')) node.textContent = t(node.dataset.i18n); for (const node of root.querySelectorAll('[data-i18n-placeholder]')) node.setAttribute('placeholder', t(node.dataset.i18nPlaceholder)); for (const node of root.querySelectorAll('[data-i18n-aria]')) node.setAttribute('aria-label', t(node.dataset.i18nAria)); }
export const SUPPORTED_LANGUAGES = Object.freeze(['zh', 'en']);
