const STORAGE_KEY = 'deep-sea-duo-language';

const COPY = Object.freeze({
  zh: Object.freeze({
    gameTitle: '深海搭档', subtitle: 'DEEP SEA DUO · 双人深海生存', roomLan: '局域网 / 热点双人直连', createRoom: '创建房间', joinRoom: '加入房间', roomCodePlaceholder: '这里会显示或粘贴连接码', roomActionConfirm: '确认连接', roomFirstPair: '首次配对：房主码 → 加入者应答码 → 房主确认', dash: '冲刺', moveHint: '左侧滑动移动', aimHint: '右侧拖动瞄准并发射', rotateTitle: '横屏体验更好', rotateBody: '请把手机转成横屏，再继续深海冒险。', connected: '局域网直连成功', hostOfferReady: '把房主连接码发给朋友', guestAnswerReady: '把加入者应答码发回房主', waitingDirect: '正在等待直连', pasteAnswer: '粘贴朋友应答码后确认', pasteOffer: '粘贴房主连接码', generateAnswer: '生成我的应答码', waiting: '等待朋友连接…', evolution: '荧光进化', chooseUpgrade: '选择一项强化', food: '食物', bossName: '深海鲨影', bossApproach: '鲨影正在逼近！', gameOverTitle: '深海暂时沉寂', survived: '存活 {seconds} 秒', restart: '点击画面重新开始', languageButton: 'EN', languageAria: '切换为英文', audioOn: '声音 开', audioOff: '声音 关', audioAria: '切换声音', level: '等级', powerup_shield: '荧光护盾', powerup_heal: '治疗气泡', powerup_wave: '清场海浪', upgrade_power_label: '泡泡增压', upgrade_power_detail: '水弹伤害 +1', upgrade_rapid_label: '连射珊瑚', upgrade_rapid_detail: '攻击间隔 -18%', upgrade_swift_label: '潮汐步伐', upgrade_swift_detail: '移动速度 +12%', upgrade_vital_label: '荧光甲壳', upgrade_vital_detail: '回复 1 点生命', upgrade_wide_label: '泡泡膨胀', upgrade_wide_detail: '水弹体积 +22%', upgrade_haste_label: '急流冲刺', upgrade_haste_detail: '冲刺冷却 -18%',
  }),
  en: Object.freeze({
    gameTitle: 'Deep Sea Duo', subtitle: 'DEEP SEA DUO · CO-OP ABYSS SURVIVAL', roomLan: 'Two-player LAN / hotspot direct link', createRoom: 'Create Room', joinRoom: 'Join Room', roomCodePlaceholder: 'Connection code appears or is pasted here', roomActionConfirm: 'Confirm Connection', roomFirstPair: 'First pairing: host offer → guest answer → host confirms', dash: 'DASH', moveHint: 'Slide left side to move', aimHint: 'Drag right side to aim & fire', rotateTitle: 'Landscape recommended', rotateBody: 'Rotate your phone to landscape before diving in.', connected: 'LAN direct link connected', hostOfferReady: 'Send the host connection code to your friend', guestAnswerReady: 'Send your answer code back to the host', waitingDirect: 'Waiting for direct connection', pasteAnswer: 'Paste your friend’s answer, then confirm', pasteOffer: 'Paste the host connection code', generateAnswer: 'Generate my answer code', waiting: 'Waiting for friend…', evolution: 'LUMINOUS EVOLUTION', chooseUpgrade: 'Choose one upgrade', food: 'food', bossName: 'Abyss Shark', bossApproach: 'The abyss shark is closing in!', gameOverTitle: 'The deep sea falls quiet', survived: 'Survived {seconds}s', restart: 'Tap the screen to restart', languageButton: '中文', languageAria: 'Switch to Chinese', audioOn: 'Sound On', audioOff: 'Sound Off', audioAria: 'Toggle sound', level: 'Lv.', powerup_shield: 'Luminous Shield', powerup_heal: 'Healing Bubble', powerup_wave: 'Clearing Wave', upgrade_power_label: 'Bubble Pressure', upgrade_power_detail: 'Bubble damage +1', upgrade_rapid_label: 'Rapid Coral', upgrade_rapid_detail: 'Attack interval -18%', upgrade_swift_label: 'Tidal Steps', upgrade_swift_detail: 'Move speed +12%', upgrade_vital_label: 'Glow Shell', upgrade_vital_detail: 'Restore 1 HP', upgrade_wide_label: 'Expanded Bubble', upgrade_wide_detail: 'Bubble size +22%', upgrade_haste_label: 'Rush Current', upgrade_haste_detail: 'Dash cooldown -18%',
  }),
});

function storage() { try { return globalThis.localStorage; } catch { return null; } }
function initialLanguage() { const saved = storage()?.getItem(STORAGE_KEY); return saved === 'en' || saved === 'zh' ? saved : 'zh'; }
let language = initialLanguage();
const listeners = new Set();
export function getLanguage() { return language; }
export function setLanguage(next, { persist = true } = {}) { language = next === 'en' ? 'en' : 'zh'; if (persist) { try { storage()?.setItem(STORAGE_KEY, language); } catch {} } for (const listener of listeners) listener(language); return language; }
export function toggleLanguage() { return setLanguage(language === 'zh' ? 'en' : 'zh'); }
export function t(key, params = {}) { const template = COPY[language][key] ?? COPY.zh[key] ?? key; return Object.entries(params).reduce((value, [name, replacement]) => value.replaceAll(`{${name}}`, String(replacement)), template); }
export function upgradeText(id) { return { label: t(`upgrade_${id}_label`), detail: t(`upgrade_${id}_detail`) }; }
export function powerupText(type) { return t(`powerup_${type}`); }
export function onLanguageChange(listener) { listeners.add(listener); return () => listeners.delete(listener); }
export function applyDocumentTranslations(root = globalThis.document) { if (!root?.querySelectorAll) return; root.documentElement?.setAttribute?.('lang', language === 'zh' ? 'zh-CN' : 'en'); for (const node of root.querySelectorAll('[data-i18n]')) node.textContent = t(node.dataset.i18n); for (const node of root.querySelectorAll('[data-i18n-placeholder]')) node.setAttribute('placeholder', t(node.dataset.i18nPlaceholder)); for (const node of root.querySelectorAll('[data-i18n-aria]')) node.setAttribute('aria-label', t(node.dataset.i18nAria)); }
export const SUPPORTED_LANGUAGES = Object.freeze(['zh', 'en']);
