const STORAGE_KEY = 'deep-sea-duo-audio';
function savedEnabled() { try { return globalThis.localStorage?.getItem(STORAGE_KEY) !== 'off'; } catch { return true; } }
function AudioContextClass() { return globalThis.AudioContext || globalThis.webkitAudioContext; }

export function createAdaptiveAudio() {
  let enabled = savedEnabled(); let ctx = null; let master = null; let musicGain = null; let sfxGain = null; let droneA = null; let droneB = null; let nextMusicAt = 0; let initializedState = false;
  let previous = { bubbles: 0, enemies: 0, hp: 3, bossHp: 0, bossActive: false, powerupMessageTimer: 0, dashTimer: 0 };
  function ensureGraph() {
    if (ctx) return true; const AC = AudioContextClass(); if (!AC) return false; ctx = new AC(); master = ctx.createGain(); musicGain = ctx.createGain(); sfxGain = ctx.createGain(); master.gain.value = enabled ? 0.72 : 0; musicGain.gain.value = 0.34; sfxGain.gain.value = 0.78; musicGain.connect(master); sfxGain.connect(master); master.connect(ctx.destination);
    const makeDrone = (frequency, gainValue, detune) => { const oscillator = ctx.createOscillator(); const filter = ctx.createBiquadFilter(); const gain = ctx.createGain(); oscillator.type = 'sine'; oscillator.frequency.value = frequency; oscillator.detune.value = detune; filter.type = 'lowpass'; filter.frequency.value = 420; gain.gain.value = gainValue; oscillator.connect(filter); filter.connect(gain); gain.connect(musicGain); oscillator.start(); return { oscillator, gain, filter }; };
    droneA = makeDrone(55, 0.032, -7); droneB = makeDrone(82.5, 0.018, 9); nextMusicAt = ctx.currentTime + 0.12; return true;
  }
  async function unlock() { if (!ensureGraph()) return false; if (ctx.state === 'suspended') { try { await ctx.resume(); } catch {} } return ctx.state === 'running'; }
  function setEnabled(next) { enabled = Boolean(next); try { globalThis.localStorage?.setItem(STORAGE_KEY, enabled ? 'on' : 'off'); } catch {} if (master && ctx) { master.gain.cancelScheduledValues(ctx.currentTime); master.gain.setTargetAtTime(enabled ? 0.72 : 0, ctx.currentTime, 0.035); } return enabled; }
  function toggle() { setEnabled(!enabled); if (enabled) unlock(); return enabled; }
  function tone(frequency, duration = 0.1, volume = 0.08, type = 'sine', slide = 1, delay = 0) { if (!ctx || !enabled || ctx.state !== 'running') return; const at = ctx.currentTime + delay; const oscillator = ctx.createOscillator(); const gain = ctx.createGain(); oscillator.type = type; oscillator.frequency.setValueAtTime(Math.max(30, frequency), at); oscillator.frequency.exponentialRampToValueAtTime(Math.max(30, frequency * slide), at + duration); gain.gain.setValueAtTime(0.0001, at); gain.gain.exponentialRampToValueAtTime(Math.max(0.0002, volume), at + Math.min(0.025, duration / 3)); gain.gain.exponentialRampToValueAtTime(0.0001, at + duration); oscillator.connect(gain); gain.connect(sfxGain); oscillator.start(at); oscillator.stop(at + duration + 0.02); }
  function chime(notes, spacing = 0.08, volume = 0.045, type = 'sine') { notes.forEach((note, index) => tone(note, 0.24, volume, type, 1.01, index * spacing)); }
  function notify(type) { if (!enabled || !ctx || ctx.state !== 'running') return; if (type === 'shot') tone(660, 0.055, 0.032, 'sine', 1.6); if (type === 'hurt') { tone(150, 0.22, 0.09, 'sawtooth', 0.55); tone(80, 0.18, 0.06, 'triangle', 0.72, 0.035); } if (type === 'enemyDown') chime([330, 495], 0.04, 0.025, 'triangle'); if (type === 'bossHit') tone(92, 0.08, 0.045, 'square', 0.78); if (type === 'bossEnter') chime([110, 82.5, 55], 0.17, 0.075, 'sawtooth'); if (type === 'bossDown') chime([220, 330, 440, 660], 0.1, 0.055, 'triangle'); if (type === 'powerup') chime([523.25, 659.25, 783.99], 0.07, 0.04, 'sine'); if (type === 'dash') { tone(220, 0.12, 0.045, 'triangle', 2.4); tone(880, 0.08, 0.02, 'sine', 0.6, 0.03); } }
  function setBossMood(active) { if (!ctx || !droneA || !droneB) return; const at = ctx.currentTime; droneA.oscillator.frequency.setTargetAtTime(active ? 43.65 : 55, at, 0.45); droneB.oscillator.frequency.setTargetAtTime(active ? 65.41 : 82.5, at, 0.45); droneA.gain.gain.setTargetAtTime(active ? 0.058 : 0.032, at, 0.35); droneB.gain.gain.setTargetAtTime(active ? 0.036 : 0.018, at, 0.35); droneA.filter.frequency.setTargetAtTime(active ? 260 : 420, at, 0.4); droneB.filter.frequency.setTargetAtTime(active ? 310 : 520, at, 0.4); }
  function scheduleMusic(game) { if (!ctx || !enabled || ctx.state !== 'running' || ctx.currentTime < nextMusicAt) return; const boss = Boolean(game.boss); const danger = Math.min(1, game.enemies.length / 18); const normalScale = [220,261.63,329.63,392,523.25]; const bossScale = [82.41,98,110,130.81,146.83]; const scale = boss ? bossScale : normalScale; const beat = boss ? 0.34 : Math.max(0.54, 0.9 - danger * 0.26); const index = Math.floor(game.time / beat) % scale.length; const root = scale[index]; tone(root, boss ? 0.24 : 0.48, boss ? 0.028 : 0.018, boss ? 'triangle' : 'sine', boss ? 0.92 : 1.005); if (!boss && index % 2 === 0) tone(root * 2, 0.72, 0.008, 'sine', 1.002, 0.08); if (boss && index % 2 === 0) tone(root / 2, 0.18, 0.03, 'sawtooth', 0.92, 0.04); nextMusicAt = ctx.currentTime + beat; }
  function sync(game, localPlayer = game.player) { if (!ctx || !enabled) return; const current = { bubbles: game.bubbles.length, enemies: game.enemies.length, hp: localPlayer.hp, bossHp: game.boss?.hp ?? 0, bossActive: Boolean(game.boss), powerupMessageTimer: game.powerupMessageTimer ?? 0, dashTimer: localPlayer.dashTimer ?? 0 }; if (initializedState) { if (current.bubbles > previous.bubbles) notify('shot'); if (current.hp < previous.hp) notify('hurt'); if (current.enemies < previous.enemies && previous.enemies > 0) notify('enemyDown'); if (!previous.bossActive && current.bossActive) notify('bossEnter'); if (previous.bossActive && !current.bossActive) notify('bossDown'); if (current.bossActive && current.bossHp < previous.bossHp) notify('bossHit'); if (current.powerupMessageTimer > previous.powerupMessageTimer + 0.4) notify('powerup'); if (current.dashTimer > previous.dashTimer + 0.04) notify('dash'); } else initializedState = true; if (current.bossActive !== previous.bossActive) setBossMood(current.bossActive); previous = current; scheduleMusic(game); }
  return { unlock, toggle, setEnabled, isEnabled: () => enabled, isUnlocked: () => Boolean(ctx && ctx.state === 'running'), notify, sync };
}
