import { WORLD } from './constants.js';
import { CORALS, JELLYFISH, currentAt, jellyPosition } from './environment.js';
import { POWERUPS } from './powerups.js';

const lerp = (a, b, t) => a + (b - a) * t;
export function resizeCanvas(canvas) { const ratio = Math.min(window.devicePixelRatio || 1, 2); canvas.width = canvas.clientWidth * ratio; canvas.height = canvas.clientHeight * ratio; return ratio; }

export function render(ctx, game) {
  const canvas = ctx.canvas; const sx = canvas.width / WORLD.width; const sy = canvas.height / WORLD.height; const scale = Math.min(sx, sy); const ox = (canvas.width - WORLD.width * scale) / 2; const oy = (canvas.height - WORLD.height * scale) / 2;
  ctx.clearRect(0, 0, canvas.width, canvas.height); ctx.save(); ctx.translate(ox, oy); ctx.scale(scale, scale);
  const bg = ctx.createLinearGradient(0, 0, WORLD.width, WORLD.height); bg.addColorStop(0, '#10124a'); bg.addColorStop(0.55, '#07183a'); bg.addColorStop(1, '#1d0c43'); ctx.fillStyle = bg; ctx.fillRect(0, 0, WORLD.width, WORLD.height);
  for (let i = 0; i < 28; i++) { const x = (i * 283) % WORLD.width; const y = (i * 191) % WORLD.height; ctx.fillStyle = i % 2 ? 'rgba(95,247,255,.09)' : 'rgba(226,112,255,.08)'; ctx.beginPath(); ctx.arc(x, y, 3 + (i % 4), 0, Math.PI * 2); ctx.fill(); }
  ctx.strokeStyle = 'rgba(146,111,255,.16)'; ctx.lineWidth = 2; for (let x = 90; x < WORLD.width; x += 160) { ctx.beginPath(); ctx.moveTo(x, WORLD.height); ctx.bezierCurveTo(x - 50, 760, x + 55, 710, x, 650); ctx.stroke(); }
  for (const coral of CORALS) { ctx.save(); ctx.translate(coral.x, coral.y); ctx.shadowColor = '#c96bff'; ctx.shadowBlur = 22; ctx.fillStyle = '#7037b9'; ctx.beginPath(); ctx.arc(0, 8, coral.radius, Math.PI, 0); ctx.lineTo(coral.radius, 28); ctx.lineTo(-coral.radius, 28); ctx.fill(); ctx.fillStyle = '#d682ff'; for (let i = -1; i <= 1; i++) { ctx.fillRect(i * coral.radius * .38 - 9, -coral.radius * .55, 18, coral.radius); } ctx.restore(); }
  for (const jelly of JELLYFISH) { const position = jellyPosition(jelly, game.time); ctx.save(); ctx.translate(position.x, position.y); ctx.shadowColor = '#82faff'; ctx.shadowBlur = 22; ctx.fillStyle = '#89f5f7'; ctx.beginPath(); ctx.arc(0, 0, position.radius, Math.PI, 0); ctx.fill(); ctx.strokeStyle = 'rgba(150,255,255,.75)'; ctx.lineWidth = 3; for (let i = -1; i <= 1; i++) { ctx.beginPath(); ctx.moveTo(i * 9, 0); ctx.quadraticCurveTo(i * 12 + 7, 22, i * 9, 38); ctx.stroke(); } ctx.restore(); }
  const current = currentAt(game.time); ctx.strokeStyle = 'rgba(126,247,255,.25)'; ctx.lineWidth = 3; for (let x = 110; x < WORLD.width; x += 200) { for (let y = 110; y < WORLD.height; y += 210) { ctx.beginPath(); ctx.moveTo(x, y); ctx.lineTo(x + current.x * .55, y + current.y * .55); ctx.stroke(); } }
  for (const food of game.food) { ctx.save(); ctx.translate(food.x, food.y); ctx.rotate(food.spin); ctx.shadowColor = '#88fff2'; ctx.shadowBlur = 18; ctx.fillStyle = '#a6fff0'; ctx.beginPath(); ctx.arc(0, 0, food.radius, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#fff'; ctx.fillRect(-3, -5, 6, 10); ctx.restore(); }
  if (game.powerup) { const item = game.powerup; const profile = POWERUPS[item.type]; ctx.save(); ctx.translate(item.x, item.y); ctx.shadowColor = profile.color; ctx.shadowBlur = 28; ctx.strokeStyle = profile.color; ctx.lineWidth = 4; ctx.beginPath(); ctx.arc(0, 0, item.radius + Math.sin(item.pulse) * 4, 0, Math.PI * 2); ctx.stroke(); ctx.fillStyle = profile.color; ctx.beginPath(); ctx.arc(0, 0, item.radius * .6, 0, Math.PI * 2); ctx.fill(); ctx.restore(); }
  for (const bubble of game.bubbles) { ctx.fillStyle = '#b8f7ff'; ctx.shadowColor = '#58edff'; ctx.shadowBlur = 15; ctx.beginPath(); ctx.arc(bubble.x, bubble.y, bubble.radius, 0, Math.PI * 2); ctx.fill(); }
  for (const enemy of game.enemies) { ctx.save(); ctx.translate(enemy.x, enemy.y); ctx.shadowColor = '#ff6bc6'; ctx.shadowBlur = 18; ctx.fillStyle = enemy.hitFlash > 0 ? '#fff' : enemy.color; if (enemy.type === 'blocker') { ctx.fillRect(-enemy.radius, -enemy.radius, enemy.radius * 2, enemy.radius * 2); } else { ctx.beginPath(); ctx.arc(0, 0, enemy.radius, 0, Math.PI * 2); ctx.fill(); } if (enemy.type === 'dasher' && enemy.dashTimer > 0) { ctx.strokeStyle = '#ffe9f9'; ctx.lineWidth = 4; ctx.beginPath(); ctx.arc(0, 0, enemy.radius + 7, 0, Math.PI * 2); ctx.stroke(); } ctx.fillStyle = '#281050'; ctx.beginPath(); ctx.arc(9, -5, 4, 0, Math.PI * 2); ctx.fill(); ctx.beginPath(); ctx.arc(-4, -7, 4, 0, Math.PI * 2); ctx.fill(); ctx.restore(); }
  if (game.boss) { const boss = game.boss; ctx.save(); ctx.translate(boss.x, boss.y); if (boss.phase === 'charge') { ctx.strokeStyle = 'rgba(255,113,167,.86)'; ctx.lineWidth = 7; ctx.setLineDash([14, 12]); ctx.beginPath(); ctx.arc(0, 0, boss.radius + 25, 0, Math.PI * 2); ctx.stroke(); ctx.setLineDash([]); } ctx.shadowColor = '#ff65a8'; ctx.shadowBlur = 38; ctx.fillStyle = boss.hitFlash > 0 ? '#fff' : '#637cf7'; ctx.beginPath(); ctx.moveTo(-boss.radius, 0); ctx.quadraticCurveTo(-20, -boss.radius, boss.radius, 0); ctx.quadraticCurveTo(-20, boss.radius, -boss.radius, 0); ctx.fill(); ctx.fillStyle = '#d0ddff'; ctx.beginPath(); ctx.moveTo(-10, -boss.radius + 8); ctx.lineTo(15, -boss.radius - 33); ctx.lineTo(30, -boss.radius + 10); ctx.fill(); ctx.fillStyle = '#07143e'; ctx.beginPath(); ctx.arc(27, -18, 7, 0, Math.PI * 2); ctx.fill(); ctx.restore(); ctx.fillStyle = 'rgba(6,6,29,.72)'; ctx.fillRect(WORLD.width / 2 - 220, 80, 440, 16); ctx.fillStyle = '#ff83bd'; ctx.fillRect(WORLD.width / 2 - 216, 84, 432 * Math.max(0, boss.hp / boss.maxHp), 8); ctx.fillStyle = '#fff'; ctx.font = 'bold 16px system-ui'; ctx.textAlign = 'center'; ctx.fillText('深海鲨影', WORLD.width / 2, 68); }
  if (game.bossMessageTimer > 0) { ctx.fillStyle = '#ffe4f4'; ctx.font = 'bold 34px system-ui'; ctx.textAlign = 'center'; ctx.fillText('鲨影正在逼近！', WORLD.width / 2, 160); }
  const p = game.player; for (let i = p.tail.length - 1; i >= 0; i--) { const part = p.tail[i]; const t = i / Math.max(1, p.tail.length); ctx.fillStyle = `hsla(${190 + t * 65}, 93%, ${58 - t * 14}%, ${0.22 + (1 - t) * 0.58})`; ctx.beginPath(); ctx.arc(part.x, part.y, lerp(8, p.radius * .72, 1 - t), 0, Math.PI * 2); ctx.fill(); }
  ctx.save(); ctx.translate(p.x, p.y); if (p.shieldTimer > 0) { ctx.strokeStyle = '#b9fbff'; ctx.lineWidth = 5; ctx.beginPath(); ctx.arc(0, 0, p.radius + 15, 0, Math.PI * 2); ctx.stroke(); } ctx.shadowColor = p.hurtTimer > 0 ? '#fff' : '#43f4ff'; ctx.shadowBlur = 25; ctx.fillStyle = p.levelShieldTimer > 0 ? '#e4c9ff' : '#4beef7'; ctx.beginPath(); ctx.arc(0, 0, p.radius, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#071b48'; ctx.beginPath(); ctx.arc(8, -6, 4, 0, Math.PI * 2); ctx.fill(); ctx.beginPath(); ctx.arc(8, 7, 4, 0, Math.PI * 2); ctx.fill(); ctx.restore();
  const r = game.remotePlayer; for (let i = r.tail.length - 1; i >= 0; i--) { const part = r.tail[i]; const t = i / Math.max(1, r.tail.length); ctx.fillStyle = `hsla(${275 + t * 25}, 88%, ${68 - t * 18}%, ${0.22 + (1-t) * .58})`; ctx.beginPath(); ctx.arc(part.x, part.y, lerp(7, r.radius * .68, 1-t), 0, Math.PI * 2); ctx.fill(); } ctx.save(); ctx.globalAlpha = r.hp > 0 ? 1 : .35; ctx.translate(r.x, r.y); ctx.shadowColor = '#c17cff'; ctx.shadowBlur = 25; ctx.fillStyle = '#a97dff'; ctx.beginPath(); ctx.ellipse(0, 0, r.radius * 1.2, r.radius * .8, 0, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#17103d'; ctx.beginPath(); ctx.arc(9, -5, 4, 0, Math.PI * 2); ctx.fill(); ctx.restore();
  if (game.state === 'gameover') { ctx.fillStyle = 'rgba(4, 4, 21, .72)'; ctx.fillRect(0, 0, WORLD.width, WORLD.height); ctx.fillStyle = '#fff'; ctx.font = 'bold 56px system-ui'; ctx.textAlign = 'center'; ctx.fillText('深海暂时沉寂', WORLD.width / 2, WORLD.height / 2 - 10); ctx.font = '28px system-ui'; ctx.fillText(`存活 ${Math.floor(game.time)} 秒 · 点击画面重新开始`, WORLD.width / 2, WORLD.height / 2 + 42); }
  ctx.restore();
}
